export const paths = {
  login: '/login',
  esqueciSenha: '/esqueci-senha',
  redefinirSenha: '/redefinir-senha',
  acessoNegado: '/acesso-negado',
  home: '/',
  administrativo: {
    lista: '/administrativo',
    novo: '/administrativo/novo',
    editar: (id: string | number) => `/administrativo/${id}/editar`,
  },
  processos: {
    lista: '/processos',
    detalhe: (id: string | number) => `/processos/${id}`,
    novo: '/processos/novo',
    editar: (id: string | number) => `/processos/${id}/editar`,
  },
  demandas: {
    lista: '/demandas',
    detalhe: (id: string | number) => `/demandas/${id}`,
    novo: '/demandas/novo',
    migrar: '/demandas/existente',
    editar: (id: string | number) => `/demandas/${id}/editar`,
  },
  estagiarios: {
    lista: '/estagiarios',
    detalhe: (id: string | number) => `/estagiarios/${id}`,
    novo: '/estagiarios/novo',
    editar: (id: string | number) => `/estagiarios/${id}/editar`,
  },
  professores: {
    lista: '/professores',
    detalhe: (id: string | number) => `/professores/${id}`,
    novo: '/professores/novo',
    editar: (id: string | number) => `/professores/${id}/editar`,
  },
  advogados: {
    lista: '/advogados',
    detalhe: (id: string | number) => `/advogados/${id}`,
    novo: '/advogados/novo',
    editar: (id: string | number) => `/advogados/${id}/editar`,
  },
  funcionarios: {
    lista: '/funcionarios',
    detalhe: (id: string | number) => `/funcionarios/${id}`,
    novo: '/funcionarios/novo',
    editar: (id: string | number) => `/funcionarios/${id}/editar`,
  },
  assistidos: {
    lista: '/assistidos',
    detalhe: (id: string | number) => `/assistidos/${id}`,
    novo: '/assistidos/novo',
    editar: (id: string | number) => `/assistidos/${id}/editar`,
  },
  configuracoes: '/configuracoes',
  usuarios: '/usuarios',
} as const;
