spring.profiles.active=${APP_PROFILE:dev}

spring.jpa.open-in-view=false
spring.data.web.pageable.max-page-size=50

api.security.token.secret=${JWT_SECRET:my-lawyer-system}

admin.email=${ADMIN_LOGIN:admin@gmail.com}
admin.password=${ADMIN_PASSWORD:1234}

springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha